apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ntp-tester
spec:
  selector:
    matchLabels:
      app: ntp-tester
  template:
    metadata:
      labels:
        app: ntp-tester
    spec:
      containers:
      - name: ntp-tester
        image: ntp-tester:alpha2
        imagePullPolicy: IfNotPresent
        env:
        - name: NTP_SERVER
          value: "pool.ntp.org"
        - name: METRICS_PORT
          value: "2112"
        - name: CHECK_DURATION
          value: "30s"
        - name: MAX_DRIFT_ALLOWED_SECONDS
          value: "2"